//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeBeloteLogic.IO.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbCard
    {
        public int Id { get; set; }
        public int DealingId { get; set; }
        public int Suit { get; set; }
        public int Side { get; set; }
        public int Stage { get; set; }
        public int BeloteCard { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<int> ShuffledSequenceNo { get; set; }
    
        public virtual DbBeloteCard DbBeloteCard { get; set; }
        public virtual DbSide DbSide { get; set; }
        public virtual DbStage DbStage { get; set; }
        public virtual DbSuit DbSuit { get; set; }
        public virtual DbDealing DbDealing { get; set; }
    }
}
