//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeBeloteLogic.IO.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbSortOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbSortOrder()
        {
            this.DbDealings = new HashSet<DbDealing>();
        }
    
        public int Value { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbDealing> DbDealings { get; set; }
        public virtual DbSortOrder DbSortOrders1 { get; set; }
        public virtual DbSortOrder DbSortOrder1 { get; set; }
    }
}
