//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeBeloteDealing.IO.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BridgeBelotEntities : DbContext
    {
        public BridgeBelotEntities()
            : base("name=BridgeBelotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DbBeloteCard> DbBeloteCards { get; set; }
        public virtual DbSet<DbCard> DbCards { get; set; }
        public virtual DbSet<DbDealing> DbDealings { get; set; }
        public virtual DbSet<DbSide> DbSides { get; set; }
        public virtual DbSet<DbSortOrder> DbSortOrders { get; set; }
        public virtual DbSet<DbStage> DbStages { get; set; }
        public virtual DbSet<DbSuit> DbSuits { get; set; }
    }
}
