USE [BridgeBelot]
GO

/****** Object:  Table [dbo].[DbBeloteCards]    Script Date: 11/06/2019 12:30:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DbBeloteCards](
	[Value] [int] NOT NULL,
	[Name] [nchar](10) NOT NULL,
	[Description] [nchar](10) NOT NULL,
	[SuitSortOrder] [int] NOT NULL,
 CONSTRAINT [PK_BeloteCards] PRIMARY KEY NONCLUSTERED 
(
	[Value] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_BeloteCards] UNIQUE CLUSTERED 
(
	[Value] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

