USE [BridgeBelot]
GO

/****** Object:  Table [dbo].[DbSortOrders]    Script Date: 11/06/2019 12:31:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DbSortOrders](
	[Value] [int] NOT NULL,
	[Name] [nchar](10) NOT NULL,
 CONSTRAINT [PK_SortOrders] PRIMARY KEY CLUSTERED 
(
	[Value] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_SortOrders] UNIQUE NONCLUSTERED 
(
	[Value] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DbSortOrders]  WITH CHECK ADD  CONSTRAINT [FK_DbSortOrders_DbSortOrders] FOREIGN KEY([Value])
REFERENCES [dbo].[DbSortOrders] ([Value])
GO

ALTER TABLE [dbo].[DbSortOrders] CHECK CONSTRAINT [FK_DbSortOrders_DbSortOrders]
GO

